version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:17"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "04:27"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    groups:
      python-dependencies:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: mcp
        update-types:
          - version-update:semver-major

  - package-ecosystem: nuget
    directories:
      - "/native/*"
      - "/tools/OpenXmlValidator"
    schedule:
      interval: weekly
      day: monday
      time: "04:37"
      timezone: Europe/Warsaw
    open-pull-requests-limit: 5
    groups:
      native-dependencies:
        patterns:
          - "*"
